export const translations={
 ru:{
 hydra:'Гидра',hydraGuideTitle:'Краткая инструкция по Гидре',hydraText:'Общая цель гильдии, основные пачки и ежедневные атаки на Гидру.',
 gameName:'Хроники Хаоса: Альянс Героев',
 teams:'Команды',teamsText:'Команды героев для глобального чемпионата и рекомендованные паки гильдии.',teamsExamplesNote:'В рейтинге — по 10 команд атаки и защиты. Рекомендованные паки гильдии пока представлены примерами.',teamsChampionship:'Рейтинг команд в глобальном чемпионате',teamsDefense:'Команды защиты',teamsAttack:'Команды атаки',teamsGuild:'Рекомендованные паки гильдии',teamsExample:'Пример',
 heroSearchLabel:'Поиск героя',heroSearch:'Имя на русском или английском…',heroRoleLabel:'Класс',heroAllRoles:'Все классы',heroRole_tank:'Танк',heroRole_warrior:'Боец',heroRole_marksman:'Стрелок',heroRole_mage:'Маг',heroRole_support:'Поддержка',heroRole_control:'Контроль',heroRole_healer:'Целитель',heroShown:'Показано героев',heroEmpty:'Герои не найдены. Измените имя или выберите другой класс.',heroSource:'Источник описания',heroSourcesNote:'Коротко об особенностях героев мобильной версии «Хроники Хаоса: Альянс Героев». Описания составлены по руководствам сообщества; ссылка на источник есть в каждой карточке.',heroOfficialSource:'Имена и классы — справка Nexters',
 guideLoading:"Загрузка инструкции…",guideLoadError:"Не удалось загрузить инструкцию. Обновите страницу или откройте файл:",guideOpen:"Открыть инструкцию",
 dungeonGuideTitle:"Инструкция по прохождению Подземелья Титанов",
brand:'Гоблины',home:'Главная',players:'Игроки',dungeon:'Подземелье',heroes:'Герои',titans:'Титаны',guildVs:'Схватка',about:'О гильдии',
 motto:'Маленькие. Шумные. Опасные.',heroTitle:'Гильдия Гоблины',heroText:'Боевые составы, прогресс и гайды для Hero Wars: Alliance.',members:'Игроков',heroPower:'Сила героев',titanPower:'Сила титанов',activity:'Активность',weekly:'за 7 дней',knownTeams:'Составов внесено',openPlayers:'Открыть список игроков',
 rosterTitle:'Игроки гильдии',search:'Поиск игрока…',sort:'Сортировка',sortActivity:'Активность',sortTotal:'Общая сила',sortHero:'Сила героев',sortTitan:'Сила титанов',sortName:'Ник',list:'Список',cards:'Карточки',heroTeam:'Команда героев',titanTeam:'Команда титанов',noData:'Состав пока не добавлен',totalPower:'Общая сила',rank:'Место',
 coming:'Раздел готовится',dungeonText:'Лечение титанов, выбор комнат, приоритеты прокачки и советы для долгого прохождения.',heroesText:'Каталог героев мобильной версии: портреты, классы и короткие описания. Найдите героя и познакомьтесь с его особенностями.',titansText:'Здесь будут советы по прокачке титанов, обликов, артефактов и составов.',guildVsText:'Здесь будет инструкция по правилам события Схватка (Guild VS), стратегия и рекомендации для гильдии.',aboutText:'Внутренний портал гильдии «Гоблины». Данные игроков перенесены из предоставленных скриншотов и будут постепенно обновляться.',backPlayers:'К игрокам',footer:'Гоблины · Вместе к победам',quick:'Разделы портала',topPlayers:'Известные боевые составы',viewAll:'Все игроки'},
 en:{
 hydra:'Hydra',hydraGuideTitle:'Quick Hydra Guide',hydraText:'The guild target, core lineups, and daily Hydra attacks.',
 gameName:'Hero Wars: Alliance',
 teams:'Teams',teamsText:'Hero teams for the Global Championship and recommended guild lineups.',teamsExamplesNote:'The rankings contain 10 attack and 10 defense teams. Recommended guild lineups are still examples.',teamsChampionship:'Global Championship team rankings',teamsDefense:'Defense teams',teamsAttack:'Attack teams',teamsGuild:'Recommended guild teams',teamsExample:'Example',
 heroSearchLabel:'Find a hero',heroSearch:'Name in Russian or English…',heroRoleLabel:'Class',heroAllRoles:'All classes',heroRole_tank:'Tank',heroRole_warrior:'Warrior',heroRole_marksman:'Marksman',heroRole_mage:'Mage',heroRole_support:'Support',heroRole_control:'Control',heroRole_healer:'Healer',heroShown:'Heroes shown',heroEmpty:'No heroes found. Try another name or class.',heroSource:'Description source',heroSourcesNote:'A quick look at heroes in Hero Wars: Alliance, the mobile game. Descriptions summarize community guides; each card links to its source.',heroOfficialSource:'Names and classes — Nexters support',
 guideLoading:"Loading guide…",guideLoadError:"Could not load the guide. Refresh the page or open the file:",guideOpen:"Open guide",
 dungeonGuideTitle:"Titan Dungeon Guide",
brand:'Goblins',home:'Home',players:'Players',dungeon:'Dungeon',heroes:'Heroes',titans:'Titans',guildVs:'Guild VS',about:'About',
 motto:'Small. Loud. Dangerous.',heroTitle:'Goblins Guild',heroText:'War teams, progress and guides for Hero Wars: Alliance.',members:'Players',heroPower:'Hero power',titanPower:'Titan power',activity:'Activity',weekly:'7 days',knownTeams:'Teams added',openPlayers:'Open player roster',
 rosterTitle:'Guild Players',search:'Search player…',sort:'Sort by',sortActivity:'Activity',sortTotal:'Total power',sortHero:'Hero power',sortTitan:'Titan power',sortName:'Nickname',list:'List',cards:'Cards',heroTeam:'Hero team',titanTeam:'Titan team',noData:'Composition not added yet',totalPower:'Total power',rank:'Rank',
 coming:'Coming soon',dungeonText:'Titan healing, room selection, upgrade priorities, and tips for longer Dungeon runs.',heroesText:'Explore the mobile hero catalog: portraits, classes, and short descriptions. Find a hero and discover what makes them unique.',titansText:'This page will contain titan, skin, artifact and team upgrade priorities.',guildVsText:'This page will contain Guild VS event rules, guild strategy and practical recommendations.',aboutText:'Internal portal for the Goblins guild. Player data was transcribed from the supplied screenshots and will be updated over time.',backPlayers:'Back to players',footer:'Goblins · Together to victory',quick:'Portal sections',topPlayers:'Known war compositions',viewAll:'All players'}
};
const storage=typeof localStorage==='undefined'?{getItem:()=>null,setItem:()=>{}}:localStorage;
let lang=storage.getItem('goblins-lang')||'ru';
export const getLanguage=()=>lang;
export const t=(key)=>translations[lang]?.[key]??key;
export function setLanguage(next){lang=next==='en'?'en':'ru';storage.setItem('goblins-lang',lang);document.documentElement.lang=lang;document.dispatchEvent(new CustomEvent('languagechange',{detail:{lang}}));applyTranslations();}
export function applyTranslations(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;el.textContent=t(key)});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));}
